### ISSUE TITLE
Updating PyPI

### ISSUE THREAD

**Issue by remram44** [brekelma/dsbox_corex#12]
Hi @brekelma!

We are trying to push the primitives to PyPI. I noticed that you registered [dsbox-corex](https://pypi.org/project/dsbox-corex/) on PyPI, but this repository contains changes that haven't been released there.

Would it be possible to release versions on PyPI with our changes, or give me access to do so? If you don't want to or don't reply, I can release the update myself under a different name.

Thanks,
-- Rémi

**Comment by brekelma** [comment]
I've hopefully granted you access on PyPi.  Let me know if there's more to do!

**Comment by remram44** [comment]
Thanks, this is very helpful!
